name = "Wolf Logistics"
prefix = "wolf_logistics"
author = "Wolf Corps"
files = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "meta.cpp"
]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip wolf_logistics_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
